name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER_ID}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PSSD}}
      run:
        docker login -u $DOCKER_USER_ID -P $DOCKER_PSSD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag piperep:v1
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER_ID}}/piperep
